### ISSUE TITLE
Issue about develop (init) script

### ISSUE THREAD

**Issue by CidChe** [adaltas/ece-webtech-2022-spring#12]
Hello I don't understand how to lauch the script named develop (init) to initialize my database. when I lauch it I have an error from axios.

I tried "npm run develop" but this issue occured
![image](https://user-images.githubusercontent.com/79929905/163168220-369259e1-385f-46ea-b509-0a13b0cd7e0c.png)

then I tried "node .\bin\init  " but this issue occured 
![image](https://user-images.githubusercontent.com/79929905/163168716-5b7a6c99-c41d-4487-9d72-507dcb1a9072.png)

Because of this, I can't initialize my database and get your script to work.

Wishing you a good week,
Cid CHELOUAH

**Comment by sergkudinov** [comment]
Hi @CidChe,

These are 2 different issues.

## The 1st one

This is because of you run your development environment on Windows and you CLI terminal is not configured to run scripts starting from relative a folder `./`. Solutions are:

- Run your development environment on any Linux (containers with Docker Compose or a VMs)
- If you stay on Windows, what is not recommended, change the command `.\bin\init` to `node .\bin\init` in your `package.json`

## The 2nd one

You have to provide a backdor to your backend to be able to test with `TEST_PAYLOAD_EMAIL` environment variable. See the implementetion in the [corrections repository](https://github.com/adaltas/ece-webtech-2022-spring#supporting-materials-corrections).

Close this issue please if it is resolved.
